-- Prune lower-impact PortCo scorecard citations from the current database.
-- Source rows are intentionally left in place because URLs may still support
-- deals, funds, or other company scorecards.

WITH pruned_sources(company_name, url) AS (
  VALUES
  ('ExteNet Systems', 'https://www.extenet.com/'),
  ('ExteNet Systems', 'https://www.extenet.com/company/'),
  ('ExteNet Systems', 'https://www.prnewswire.com/news-releases/extenet-systems-announces-successful-closing-of-manulife-investment-301287806.html'),
  ('ExteNet Systems', 'https://extenet.com/'),
  ('ExteNet Systems', 'https://extenet.com/extenet-systems-and-mgm-resorts-announce-nationwide-connectivity-partnership/'),
  ('ExteNet Systems', 'https://extenet.com/extenet-systems-welcomes-john-hancock-as-a-strategic-investor/'),
  ('ExteNet Systems', 'https://extenet.com/extenet-systems-announces-successful-closing-of-manulife-investment/'),
  ('ExteNet Systems', 'https://www.manulifeim.com/institutional/global/en/strategies/private-markets/infrastructure/infrastructure-team'),
  ('ExteNet Systems', 'https://www.prnewswire.com/news-releases/extenet-systems-announces-capital-restructuring-300117742.html'),
  ('ExteNet Systems', 'https://wirelessestimator.com/articles/2026/pilot-fiber-to-acquire-carved-out-enterprise-fiber-unit-from-digitalbridge-backed-extenet/'),
  ('Generate Capital', 'https://generatecapital.com/'),
  ('Generate Capital', 'https://generatecapital.com/news/leading-global-institutions-invest-in-a-clean-energy-future-with-generate-capital/'),
  ('Generate Capital', 'https://www.generatecapital.com/'),
  ('Generate Capital', 'https://www.bloomberg.com/news/articles/2021-09-14/generate-capital-raises-2-billion'),
  ('Generate Capital', 'https://www.australiansuper.com/global-investors/who-we-are/north-america'),
  ('Generate Capital', 'https://generatecapital.com/wp-content/uploads/2022/04/Generate-Green-Financing-Framework-v2.pdf'),
  ('Generate Capital', 'https://generatecapital.com/wp-content/uploads/2022/06/Generate-Green-Financing-Framework_vFFF-clean.pdf'),
  ('Generate Capital', 'https://www.businesswire.com/news/home/20240130298422/en/Leading-Global-Institutions-Invest-in-a-Clean-Energy-Future-With-Generate-Capital'),
  ('Generate Capital', 'https://generatecapital.com/generate-capital-announces-sale-of-equinox-growers-greenhouse-facility-to-taylor-farms/'),
  ('Generate Capital', 'https://www.globenewswire.com/news-release/2026/04/29/3283723/0/en/monarch-private-capital-and-generate-capital-announce-104-mw-energy-investment-portfolio.html'),
  ('Puget Sound Energy', 'https://www.macquarie.com/us/en/about/news/2021/macquarie-asset-management-and-ontario-teachers-sign-agreement-to-acquire-stake-in-puget-holdings.html'),
  ('Puget Sound Energy', 'https://www.globenewswire.com/news-release/2018/08/08/1549345/0/en/OMERS-Infrastructure-Announces-Investment-in-Puget-Sound-Energy.html'),
  ('Puget Sound Energy', 'https://www.pse.com/'),
  ('Puget Sound Energy', 'https://www.pse.com/en/about-us/our-history'),
  ('Puget Sound Energy', 'https://www.pse.com/-/media/PDFs/PugetEnergy/PE-10K-20231231.pdf'),
  ('Puget Sound Energy', 'https://www.pugetenergy.com/document/2022_NYC_Roadshow.pdf'),
  ('Puget Sound Energy', 'https://www.pse.com/-/media/PDFs/Sustainability/2025_PSERY24SustainabilityReport.pdf'),
  ('Puget Sound Energy', 'https://www.aimco.ca/insights/aimco-increases-stake-in-puget-sound-energy'),
  ('Puget Sound Energy', 'https://assets.ctfassets.net/lyt4cjmefjno/5aorUTYWwgPMIGc9cNPx9r/8518334d4637dbde57c10a376b60c10c/puget_investment.pdf'),
  ('Vantage Data Centers', 'https://www.prnewswire.com/news-releases/consortium-of-digital-bridge-psp-investments-and-tiaa-investments-acquires-vantage-data-centers-300429476.html'),
  ('Vantage Data Centers', 'https://vantage-dc.com/news/colony-capital-and-vantage-data-centers-to-form-strategic-partnership-to-advance-data-center-growth/'),
  ('Vantage Data Centers', 'https://www.digitalbridge.com/portfolio/vantage-data-centers-yieldco'),
  ('Vantage Data Centers', 'https://ir.digitalbridge.com/news-releases/news-release-details/digitalbridge-announces-expansion-vantage-sdc-platform/'),
  ('Vantage Data Centers', 'https://ir.digitalbridge.com/news-releases/news-release-details/digitalbridge-completes-deconsolidation-vantage-sdc/'),
  ('Vantage Data Centers', 'https://www.gcmgrosvenor.com/wp-content/uploads/GCM-Grosvenor-2024-Labor-and-Economic-Impact-Report.pdf'),
  ('Vantage Data Centers', 'https://vantage-dc.com/news/vantage-data-centers-announces-6-4-billion-equity-investment-round-led-by-digitalbridge-and-silver-lake/'),
  ('Vantage Data Centers', 'https://ir.digitalbridge.com/news-releases/news-release-details/digitalbridge-backed-portfolio-company-vantage-data-centers/'),
  ('Vantage Data Centers', 'https://vantage-dc.com/company/contact-us/'),
  ('Duquesne Light Company', 'https://www.duquesnelight.com/docs/default-source/default-document-library/duquesne-light-company_2023-esg-report_vfinal.pdf'),
  ('Duquesne Light Company', 'https://www.duquesnelight.com/docs/default-source/default-document-library/dlc-corporate-responsibility-report.pdf'),
  ('Duquesne Light Company', 'https://www.puc.pa.gov/pcdocs/1700404.pdf'),
  ('Duquesne Light Company', 'https://www.duquesnelight.com/docs/default-source/default-document-library/duquesne-light-company_2023-esg-report_vfinal.pdf?sfvrsn=2e9aee44_1'),
  ('Duquesne Light Company', 'https://www.duquesnelight.com/'),
  ('Duquesne Light Company', 'https://www.puc.pa.gov/pcdocs/1748560.pdf'),
  ('Duquesne Light Company', 'https://www.manulifeim.com/institutional/global/en/strategies/private-markets/infrastructure/infrastructure-team'),
  ('Duquesne Light Company', 'https://duquesnelight.com/docs/default-source/default-document-library/Duquesne-Light-Distribution-System-Generation-Interconnection-Requirements.pdf'),
  ('Rio Grande LNG', 'https://www.sidley.com/en/newslanding/newsannouncements/2023/07/sidley-represents-gic-in-its-commitment-to-nextdecade-new-us18-billion-lng-project'),
  ('Rio Grande LNG', 'https://investors.next-decade.com/news-releases/news-release-details/nextdecade-announces-positive-final-investment-decision-and'),
  ('Rio Grande LNG', 'https://totalenergies.com/news/press-releases/united-states-totalenergies-and-its-partners-make-final-investment-decision'),
  ('Rio Grande LNG', 'https://www.global-infra.com/news/nextdecade-announces-positive-final-investment-decision-on-rio-grande-lng-phase-1/'),
  ('Rio Grande LNG', 'https://www.next-decade.com/rio-grande-lng/'),
  ('Rio Grande LNG', 'https://www.global-infra.com/media/press-releases/2023/07/12/global-infrastructure-partners-announces-investment-in-rio-grande-lng-phase-1/'),
  ('DataBank', 'https://www.databank.com/'),
  ('DataBank', 'https://fr.swisslife-am.com/en/home/news/france/corporate/company-news/2022/0617_databank.html'),
  ('DataBank', 'https://www.australiansuper.com/-/media/australian-super/files/about-us/media-releases/2024/australiansuper-agrees-to-invest-2-point-2-billion-in-databank.pdf'),
  ('DataBank', 'https://www.digitalbridge.com/news/2025-01-30-digitalbridge-announces-participation-in-databank-financing'),
  ('DataBank', 'https://www.goodman.com/investor-centre/announcements-media/2026/databank-and-goodman-group-partner-to-open-new-landmark-data-center-in-los-angeles'),
  ('Gemini Solar + Storage', 'https://www.key.com/businesses-institutions/our-transactions/deals.primergy.html'),
  ('Gemini Solar + Storage', 'https://www.quinbrook.com/news-insights/quinbrook-closes-funding-partnership-for-primergy-s-gemini-solar-storage-project/'),
  ('Gemini Solar + Storage', 'https://www.eia.gov/todayinenergy/detail.php?id=64126'),
  ('Gemini Solar + Storage', 'https://www.quinbrook.com/news-insights/historic-gemini-solar-energy-storage-project-reaches-commercial-operations-in-nevada/'),
  ('Gemini Solar + Storage', 'https://www.primergypower.com/news/quinbrook-and-primergy-solar-partner-with-apg-on-gemini-solar-storage-project'),
  ('Gemini Solar + Storage', 'https://www.primergypower.com/news'),
  ('Phoenix Tower International', 'https://www.phoenixintnl.com/news/blackstone-infrastructure-partners-acquires-stake-in-phoenix-tower-international'),
  ('Phoenix Tower International', 'https://www.aoshearman.com/en/news/allen-overy-advises-grain-blackrock-on-their-strategic-investment-in-phoenix-tower-international'),
  ('Phoenix Tower International', 'https://www.stblaw.com/about-us/news/view/2024/04/03/grain-management-and-blackrock-invest-in-phoenix-tower-international'),
  ('Phoenix Tower International', 'https://www.phoenixintnl.com/news/phoenix-tower-international-closes-on-1978-sites-across-france'),
  ('Phoenix Tower International', 'https://www.phoenixintnl.com/news/phoenix-tower-international-earns-great-place-to-work-certification-across-10-markets-usa-english'),
  ('Brazos Midstream', 'https://www.efmidstream.com/portfolio-companies/current/brazos-midstream'),
  ('Brazos Midstream', 'https://brazosmidstream.com/news/brazos-midstream-significantly-expands-midland-basin-natural-gas-gathering-and-processing'),
  ('Brazos Midstream', 'https://brazosmidstream.com/news/brazos-midstream-agrees-sell-delaware-basin-subsidiaries-morgan-stanley-infrastructure-175'),
  ('Brazos Midstream', 'https://brazosmidstream.com/news'),
  ('Tallgrass Energy', 'https://www.tallgrassenergy.com/'),
  ('Tallgrass Energy', 'https://www.blackstone.com/news/press/blackstone-infrastructure-partners-to-acquire-tallgrass-energy/'),
  ('Tallgrass Energy', 'https://www.blackstone.com/news/press/blackstone-infrastructure-partners-enters-into-definitive-agreement-to-acquire-controlling-interest-in-tallgrass-energy/'),
  ('Tallgrass Energy', 'https://www.tallgrass.com/'),
  ('Tallgrass Energy', 'https://tallgrass.com/newsroom/press-releases/blackstone-infrastructure-partners-enters-into-definitive-agreement-to-acquire-controlling-interest-in-tallgrass-energy'),
  ('Chicago Parking Meters, LLC', 'https://www.morganstanley.com/press-releases/chicago-parking-meters-llc-selected-as-winning-bidder-for-the-chicago-metered-parking-system_045f9d28-c142-11dd-b3a2-8df06e0b6eda'),
  ('Chicago Parking Meters, LLC', 'https://www.morganstanley.com/im/en-us/institutional-investor/about-us/people-and-teams/investment-teams/infrastructure-team.html'),
  ('Chicago Parking Meters, LLC', 'https://parkchicago.com/'),
  ('Chicago Parking Meters, LLC', 'https://www.morganstanley.com/im/en-la/intermediary-investor/companies/chicago-parking-meters.html'),
  ('InTransit BC', 'https://thecdm.ca/partners/industry/intransit-bc'),
  ('InTransit BC', 'https://ca.linkedin.com/company/intransit-bc'),
  ('InTransit BC', 'https://cdpqinfra.com/sites/cdpqinfrad8/files/2021-10/03-CDPQI-AAM-EN_notice_to_market.pdf'),
  ('InTransit BC', 'https://www.snclavalin.com/~/media/Files/S/SNC-Lavalin/download-centre/investors/annual-reports/2016/snc_annualreport2016_en.pdf'),
  ('Portland Natural Gas Transmission System', 'https://www.tcenergy.com/announcements/2024/2024-03-04-tc-energy-announces-sale-of-portland-natural-gas-transmission-system/'),
  ('Portland Natural Gas Transmission System', 'https://northeastgas.org/files/galleries/PNGTS.pdf'),
  ('Portland Natural Gas Transmission System', 'https://www.pngts.com/who-we-are'),
  ('Portland Natural Gas Transmission System', 'https://www.bracewell.com/news-events/bracewell-advises-tc-energy-in-sale-of-portland-natural-gas-transmission-system/'),
  ('Sempra Infrastructure Partners, LP', 'https://www.semprainfrastructure.com/about-us'),
  ('Sempra Infrastructure Partners, LP', 'https://www.semprainfrastructure.com/port-arthur-lng'),
  ('Sempra Infrastructure Partners, LP', 'https://www.sempra.com/newsroom/press-releases/sempra-announces-strategic-transactions-advancing-goal-building-leading-us'),
  ('Third Coast Infrastructure', 'https://www.infrapppworld.com/update/arclight-closes-continuation-fund-with-us407-million'),
  ('Third Coast Infrastructure', 'https://www.third-coast.com/post/third-coast-super-holdings-strengthens-financial-position-with-25-million-loan-upsize-and-repricing'),
  ('Third Coast Infrastructure', 'https://www.third-coast.com/about-us'),
  ('Third Coast Infrastructure', 'https://pestakeholder.org/news/private-equity-owns-company-responsible-for-latest-gulf-oil-spill/'),
  ('ACES Delta', 'https://www.otpp.com/en-ca/modals/portfolio/aces-delta/'),
  ('ACES Delta', 'https://aces-delta.com/'),
  ('ACES Delta', 'https://www.energy.gov/edf/advanced-clean-energy-storage'),
  ('Aligned Data Centers', 'https://www.blackrock.com/corporate/newsroom/press-releases/article/corporate-one/press-releases/blackrock-acquires-aligned-data-centers'),
  ('Aligned Data Centers', 'https://www.macquarie.com/au/en/about/company/macquarie-asset-management/our-portfolio/aligned-data-centers.html'),
  ('Atlantica Sustainable Infrastructure plc', 'https://www.ecpgp.com/equity/portfolio/atlantica'),
  ('Atlantica Sustainable Infrastructure plc', 'https://www.ecpgp.com/'),
  ('Cascade Power Project', 'https://www.axiuminfra.com/portfolio-assets/?lang=en'),
  ('Cascade Power Project', 'https://www.axiuminfra.com/wp-content/uploads/2020/08/Media-Release_Axium_Cascade-Power-Project.pdf'),
  ('Cascade Power Project', 'https://www.pcl.com/ca/en/our-work/cascade-power-project'),
  ('Catalyze', 'https://catalyze.com/'),
  ('Catalyze', 'https://www.encapinvestments.com/news/catalyze-announces-acquisition-sol-alliance-expanding-development-capabilities-and-project'),
  ('Compass Datacenters', 'https://www.compassdatacenters.com/news/brookfield-infrastructure-and-ontario-teachers-to-acquire-compass-datacenters-from-redbird-capital-partners-and-azrieli-group/'),
  ('Compass Datacenters', 'https://www.otpp.com/en-ca/investments/our-advantage/our-performance-and-track-record/major-investments/'),
  ('Compass Datacenters', 'https://www.compassdatacenters.com/'),
  ('FirstEnergy Transmission, LLC', 'https://www.firstenergycorp.com/newsroom/news_articles/firstenergy-announces--3-5-billion-equity-capital-agreement-to-f.html'),
  ('FirstEnergy Transmission, LLC', 'https://www.tradepractitioner.com/2024/02/cfius-brookfield-infrastructure-partners-lp-and-firstenergy-transmission-llc-2/'),
  ('Golden State Wind', 'https://www.cppinvestments.com/newsroom/golden-state-wind-a-joint-venture-of-ocean-winds-and-cpp-investments-wins-2-gw-california-wind-energy-lease/'),
  ('Golden State Wind', 'https://www.vineyardoffshore.com/resource/offshore-wind-energy-to-power-california/'),
  ('Golden State Wind', 'https://www.vineyardoffshore.com/article/vineyard-offshore-statement-on-massachusetts-procurement-awards/'),
  ('Oncor Electric Delivery Company LLC', 'https://www.oncor.com/content/dam/oncorwww/documents/investorrelations/financial-news/Q4%202018%20Oncor%20Earnings%20Release%20-%20FINAL%20B-%202.25.19.pdf'),
  ('Oncor Electric Delivery Company LLC', 'https://www.quinnemanuel.com/the-firm/our-notable-victories/june-2020-appellate-victory-for-omers-pension-fund-in-delaware-supreme-court/'),
  ('Vertical Bridge', 'https://ir.digitalbridge.com/news-releases/news-release-details/vertical-bridge-completes-33-billion-tower-transaction-verizon/'),
  ('Vertical Bridge', 'https://www.verticalbridge.com/')
)
DELETE FROM "Citation" c
USING "Company" co, "Source" s, pruned_sources p
WHERE c."companyId" = co."id"
  AND c."sourceId" = s."id"
  AND co."name" = p.company_name
  AND s."url" = p.url;
