import { completenessCheckNames, scorecardResearchResultSchema } from "./schema";

export const HASH_A = "a".repeat(64);
export const HASH_B = "b".repeat(64);

const verified = (value: string | number, sourceIds: string[]) => ({
  disclosureStatus: "VERIFIED" as const,
  value,
  sourceIds,
  notes: "Verified from the cited direct source.",
});

const notDisclosed = (notes = "Not publicly disclosed after a direct-source search.") => ({
  disclosureStatus: "NOT_PUBLICLY_DISCLOSED" as const,
  value: null,
  sourceIds: [],
  notes,
});

const notApplicable = (notes: string) => ({
  disclosureStatus: "NOT_APPLICABLE" as const,
  value: null,
  sourceIds: [],
  notes,
});

export function validResearchResult() {
  return scorecardResearchResultSchema.parse({
    schemaVersion: 1,
    artifactType: "SCORECARD_REFRESH_RESEARCH_RESULT",
    methodologyVersion: "PORTCO_SCORECARD_GPT56_PRO_V1",
    asOfDate: "2026-08-03",
    taskIndex: 1,
    taskId: "company:company-1",
    companyId: "company-1",
    requestedCompany: "Example Infrastructure, LLC",
    companySnapshotHash: HASH_A,
    sourceDatabaseSnapshotHash: HASH_B,
    taskStatus: "COMPLETE",
    blockers: [],
    executionAttestation: {
      surface: "CHATGPT_WEB_APP",
      conversationUrl: "https://chatgpt.com/c/example-scorecard",
      model: "GPT-5.6 Sol",
      mode: "Pro",
      freshConversation: true,
      webResearchUsed: true,
      verifiedAt: "2026-08-03T14:00:00.000Z",
    },
    identityDecision: {
      decision: "KEEP_CANONICAL",
      canonicalName: "Example Infrastructure, LLC",
      aliases: ["Example Infrastructure"],
      predecessorNames: [],
      successorNames: [],
      mergeTargetCompanyId: null,
      mergeTargetCanonicalName: null,
      platformBoundary: "Count the operating platform once and exclude its underlying projects.",
      rationale: "Official company and owner sources use the same canonical identity.",
      sourceIds: ["source-owner"],
    },
    recommendedCompany: {
      name: "Example Infrastructure, LLC",
      website: verified("https://example.com/company", ["source-owner"]),
      sector: "Utilities",
      subsector: "Water utility services",
      region: "North America",
      country: "United States",
      countryTags: ["United States"],
      headquarters: verified("Austin, Texas", ["source-owner"]),
      yearFounded: verified(2001, ["source-owner"]),
      companyStatus: "ACTIVE",
      description: verified("Example owns and operates regulated water infrastructure in Texas.", ["source-owner"]),
      productsAndServices: verified("Potable water and wastewater utility services.", ["source-owner"]),
      customersAndEndMarkets: verified("Residential and commercial utility customers.", ["source-owner"]),
      geographicFootprint: verified("Central Texas.", ["source-owner"]),
      operatingScale: notDisclosed(),
    },
    ownerships: [{
      ownerName: "Example Infrastructure Fund Manager",
      requestedManagers: ["BlackRock"],
      state: "CLOSED_ACTIVE",
      isCurrentLegalOwner: true,
      infrastructureStrategyBasis: verified("Held through the manager's direct infrastructure strategy.", ["source-owner"]),
      fundName: notDisclosed(),
      vehicleName: notDisclosed(),
      stake: notDisclosed(),
      announcedAt: verified("2020-01-15", ["source-owner"]),
      closedAt: verified("2020-03-02", ["source-owner"]),
      investmentYear: verified(2020, ["source-owner"]),
      exitAt: notApplicable("The manager remains the current legal owner."),
      exitYear: notApplicable("The manager remains the current legal owner."),
      ownershipEvidenceSourceIds: ["source-owner"],
    }],
    pendingTransactions: [],
    transactionState: "CLOSED_ACTIVE",
    overview: verified("Example is an active Texas water utility platform owned by an infrastructure manager.", ["source-owner"]),
    milestones: [
      {
        date: "2001",
        sortDate: "2001-01-01",
        datePrecision: "YEAR",
        event: "Example Infrastructure was founded.",
        category: "Founding",
        materialityRationale: "Establishes the platform's operating history.",
        sourceIds: ["source-milestone"],
      },
      {
        date: "Mar 2, 2020",
        sortDate: "2020-03-02",
        datePrecision: "DAY",
        event: "Example Infrastructure Fund Manager completed its acquisition of the company.",
        category: "Acquisition",
        materialityRationale: "Establishes the current ownership period.",
        sourceIds: ["source-owner"],
      },
    ],
    management: {
      disclosureStatus: "VERIFIED",
      executives: [{
        name: "Alex Example",
        title: "Chief Executive Officer",
        isCurrent: true,
        startDate: notDisclosed("The current role is verified, but the start date is not public."),
        sourceIds: ["source-management"],
      }],
      notes: "Only the currently verified C-suite executive is included.",
    },
    citations: [
      {
        sourceId: "source-owner",
        url: "https://example.com/company",
        title: "Example Infrastructure company profile",
        publisher: "Example Infrastructure Fund Manager",
        sourceTier: "PRIMARY",
        health: "WORKING",
        finalUrl: null,
        publishedAt: "2020-03-02",
        retrievedAt: "2026-08-03",
        evidenceLabel: "Official ownership and company profile",
        evidenceSummary: "Supports identity, company profile, infrastructure ownership, and investment timing.",
        purposes: ["IDENTITY", "OWNERSHIP_CURRENT", "OWNERSHIP_TRANSACTION", "INFRASTRUCTURE_STRATEGY", "COMPANY_PROFILE", "OPERATIONS_SCALE", "MILESTONE", "DEAL_RECONCILIATION"],
        isPrimary: true,
      },
      {
        sourceId: "source-milestone",
        url: "https://example.com/company-history",
        title: "Example Infrastructure history",
        publisher: "Example Infrastructure",
        sourceTier: "PRIMARY",
        health: "WORKING",
        finalUrl: null,
        publishedAt: null,
        retrievedAt: "2026-08-03",
        evidenceLabel: "Official company history",
        evidenceSummary: "Supports the founding milestone.",
        purposes: ["MILESTONE"],
        isPrimary: false,
      },
      {
        sourceId: "source-management",
        url: "https://example.com/leadership",
        title: "Example Infrastructure leadership",
        publisher: "Example Infrastructure",
        sourceTier: "PRIMARY",
        health: "WORKING",
        finalUrl: null,
        publishedAt: null,
        retrievedAt: "2026-08-03",
        evidenceLabel: "Current leadership page",
        evidenceSummary: "Supports the current chief executive.",
        purposes: ["MANAGEMENT"],
        isPrimary: false,
      },
    ],
    relatedDeals: [{
      disposition: "MATCHED_EXISTING",
      dealId: "deal-1",
      legacyId: null,
      title: "Acquisition of Example Infrastructure",
      transactionDate: "2020-03-02",
      rationale: "The existing deal matches the legal close.",
      sourceIds: ["source-owner"],
    }],
    missingDealsForSeparateReview: [],
    beforeAfterDifferences: [{
      entity: "COMPANY",
      fieldPath: "description",
      changeType: "CORRECT",
      before: "Old description",
      after: "Example owns and operates regulated water infrastructure in Texas.",
      rationale: "Replaces generic wording with a sourced operating description.",
      sourceIds: ["source-owner"],
    }],
    proposedRemovals: [],
    proposedMerges: [],
    unresolvedQuestions: ["The ownership percentage is not publicly disclosed."],
    applicationRecommendation: "APPLY_READY",
    confidence: "HIGH",
    completenessChecks: Object.fromEntries(completenessCheckNames.map((name) => [name, true])),
  });
}

export function validPromptContext() {
  const result = validResearchResult();
  return {
    schemaVersion: 1 as const,
    asOfDate: result.asOfDate,
    taskIndex: result.taskIndex,
    taskId: result.taskId,
    companyId: result.companyId,
    canonicalName: result.requestedCompany,
    aliases: ["Example Infrastructure"],
    assignedManager: "BlackRock",
    allApplicableManagers: ["BlackRock", "Global Infrastructure Partners"],
    companySnapshotHash: result.companySnapshotHash,
    sourceDatabaseSnapshotHash: result.sourceDatabaseSnapshotHash,
    executionAttestation: result.executionAttestation,
    currentScorecardSnapshot: { name: result.requestedCompany, status: "Active" },
    currentOwnershipHistory: [{ owner: "Example Infrastructure Fund Manager", isActive: true }],
    managerCensusEvidence: [{ manager: "BlackRock", disposition: "EXISTING_VERIFIED" }],
    existingSeedRecord: { name: result.requestedCompany },
    relatedDatabaseDeals: [{ id: "deal-1" }],
    knownFlags: ["VERIFY_OWNER_STAKE"],
  };
}
